# Define UI
ui <- fluidPage(
  
  # Application title
  titlePanel("Do I Suck Or Does My Team Suck?"),
  
  sidebarLayout(
    
    # Sidebar Panel for Inputs ----
    sidebarPanel(
      textInput("input_summoner_name",
                  "Summoner Name",
                  value = 'w6f'),
      # selectInput("input_region",
      #             "Region Name",
      #             choices = c('na1'),
      #             selected = 'na1'),
      actionButton('button_reload','Load Summoner', icon = icon("play-circle")),
      hr(),
      sliderInput('input_games_back',
                  'Latest How Many Games',
                  min = 1,
                  max = 1000,
                  value = 1000,
                  step = 1),
      selectInput('input_champ_select',
                  'What Champs',
                  choices = c('Diana','Cassiopeia'),
                  multiple = TRUE,
                  selectize = TRUE)
    ),
    
    # Main Panel for Plots ----
    mainPanel(
      plotOutput("plot_top"),
      plotOutput("plot_bottom")
    )
  )
)

# Server logic
server <- function(session, input, output) {
  
  # Initialize Data Reactive ----
  my_data <- reactiveVal({
    
    # Read CSV generated by Python
    df1 <- readRDS('Initial Data.RDS')
    
    # Wrangle Date
    df1 <- wrangle_data(df1, 'w6f')
    
    # Update Champion Select Input Choices
    updateSelectizeInput(session, 'input_champ_select', 
                         choices = get_champ_list(df1, 'w6f'))
    
    # Return Data
    df1
    
  })
  
  # New API pull (New Summoner Selected) ----
  observeEvent(input$button_reload, {
    
    # Store inputted summoner and region
    new_summoner <- input$input_summoner_name
    # new_region <- input$input_region
    
    # Python API query for new data and read that data
    print(paste0('Start Python API Query For: ',new_summoner,' @ ',Sys.time()))
    get_api_data(new_summoner,'na1')
    print(paste0('End Python API Query For: ',new_summoner,' @ ',Sys.time()))
    df1 <- tibble(read.csv('Temp - Raw API Data.csv'))
    
    # Wrangle Data
    df1 <- wrangle_data(df1, new_summoner)
    
    # Store wrangled data in reactive
    my_data(df1)
    
    # Update Slider max and value according to # of unique games in data
    val <- length(unique(df1$gameCreation))
    updateSliderInput(session, "input_games_back", value = val, max = val)
    
    # Update Champion Select Input Choices
    updateSelectizeInput(session, 'input_champ_select', 
                         choices = get_champ_list(df1, new_summoner))
  }, 
  ignoreInit = TRUE)
  
  # Plot - Bottom Output ----
  output$plot_bottom <- renderPlot({
    
    # Get Data
    df1 <- my_data()
    
    # Filter by Games Back Input
    df1 <- df1 %>%
      arrange(desc(gameCreation)) %>%
      slice_head(n = input$input_games_back*10)
    
    # Filter to Champion Selection
    df1 <- df1 %>%
      filter_by_champion(my_champion_list = isolate(input$input_champ_select))
    
    # Filter to only your position
    df1 <- df1 %>%
      filter(my_position==TRUE)
    
    # Calculate Column Indicating it's the chosen summoner  
    df1 <- df1 %>%
      mutate(me=case_when(summonerName==isolate(input$input_summoner_name) ~ TRUE,
                          TRUE ~ FALSE))
    
    # Change Values and Column Names for Display
    df1 <- df1 %>%
      mutate(me = case_when(me==TRUE ~ 'Myself',TRUE ~ 'Opponent')) %>% 
      rename(Player = me) %>% 
      mutate(win = case_when(win=='True' ~ 'Win',TRUE ~ 'Loss')) %>% 
      rename(`Game Result` = win) %>% 
      rename(`KDA` = kda)
    saveRDS(df1,'my_check_BOT.rds')
    
    # Make Plot
    df1 %>%
      ggplot(aes(fill=Player, y=KDA, x=`Game Result`)) + 
      geom_bar(position="dodge", stat="identity")
    
  })
  
  #  Plot - Top Output ----
  output$plot_top <- renderPlot({
    
    # Get Data
    df1 <- my_data()
    
    # Filter by Games Back Input
    df1 <- df1 %>%
      arrange(desc(gameCreation)) %>%
      slice_head(n = input$input_games_back*10)
    
    # Filter by Champion Selection
    df1 <- df1 %>%
      filter_by_champion(my_champion_list = isolate(input$input_champ_select))
    
    # Change Values and Column Names for Display
    df1 <- df1 %>%
      mutate(my_team = case_when(my_team==TRUE ~ 'My Team',TRUE ~ 'Opposing Team')) %>% 
      rename(`Team` = my_team) %>% 
      rename(`Role` = teamPosition) %>% 
      mutate(Role = str_to_title(Role)) %>%    
      rename(`Solo Kills` = soloKills) %>%
      mutate(Role = case_when(Role=='Utility' ~ 'Support',TRUE ~ Role)) %>% 
      mutate(my_position = case_when(my_position==TRUE ~ 'Me Playing',
                                     TRUE ~ 'My Team Playing'))
      
    # Manually Order Positions
    df1$Role <- factor(df1$Role, levels=c("Top", "Jungle","Middle","Bottom",
                                                            "Support"))
    # Filter Out Bad Data
    df1 <- df1 %>%
      filter(is.na(Role)==FALSE)
    saveRDS(df1,'my_check_TOP.rds')
    # Make Plot
    df1 %>%
      ggplot(aes(fill=Team, y=`Solo Kills`, x=Role)) + 
        geom_bar(position="dodge", stat="identity") +
        facet_grid(rows = vars(my_position))
  })
}

# Complete app with UI and server components
shinyApp(ui, server)