# Define UI
ui <- fluidPage(
  
  # Application title
  # titlePanel("Do I Suck Or Does My Team Suck?"),
  
  sidebarLayout(
    
    # Sidebar Panel for Inputs ----
    sidebarPanel(width = 3, style="margin-top: 10px",
      textInput("input_summoner_name",
                  "Summoner Name",
                  value = 'w6f'),
      # selectInput("input_region",
      #             "Region Name",
      #             choices = c('na1'),
      #             selected = 'na1'),
      actionButton('button_reload','Load Summoner', icon = icon("play-circle")),
      hr(),
      sliderInput('input_games_back',
                  'Latest How Many Games',
                  min = 1,
                  max = 100,
                  value = 100,
                  step = 1),
      selectInput('input_champ_select',
                  'What Champs',
                  choices = c('Diana','Cassiopeia'),
                  multiple = TRUE,
                  selectize = TRUE),
      uiOutput("output_selection_helptext")
    ),
    
    # Main Panel for Plots ----
    mainPanel(width=9,
      fluidRow(
        uiOutput("output_story"),
        hr()
      ),
      fluidRow(
        column(7,
          div(style="font-size: 22px; text-align: center",'Solo Kills'),
          div(class="help-block",style='font-size: 14px;',
              includeHTML("inst/Solo Kills.html")),
          plotOutput("plot_top")),
        column(5,
          div(style="font-size: 22px; text-align: center",'KDA'),
          div(class="help-block",style='font-size: 14px;',
              includeHTML("inst/KDA.html")),
          plotOutput("plot_bottom"))
      )
    )
  )
)

# Server logic
server <- function(session, input, output) {
  
  # Initialize Data Reactive ----
  my_data <- reactiveVal({
    
    # Read CSV generated by Python
    df1 <- readRDS('Initial Data.RDS')
    
    # Wrangle Date
    df1 <- wrangle_data(df1, 'w6f')
    
    # Update Champion Select Input Choices
    updateSelectizeInput(session, 'input_champ_select', 
                         choices = get_champ_list(df1, 'w6f'))
    
    # Return Data
    df1
    
  })
  
  # New API Pull (New Summoner Selected) ----
  observeEvent(input$button_reload, {
    
    # Store inputted summoner and region
    new_summoner <- input$input_summoner_name
    # new_region <- input$input_region
    
    # Python API query for new data and read that data
    print(paste0('Start Python API Query For: ',new_summoner,' @ ',Sys.time()))
    get_api_data(new_summoner,'na1')
    print(paste0('End Python API Query For: ',new_summoner,' @ ',Sys.time()))
    df1 <- tibble(read.csv('Temp - Raw API Data.csv'))
    
    # Wrangle Data
    df1 <- wrangle_data(df1, new_summoner)
    
    # Store wrangled data in reactive
    my_data(df1)
    
    # Update Slider max and value according to # of unique games in data
    val <- length(unique(df1$gameCreation))
    updateSliderInput(session, "input_games_back", value = val, max = val)
    
    # Update Champion Select Input Choices
    updateSelectizeInput(session, 'input_champ_select', 
                         choices = get_champ_list(df1, new_summoner))
  }, 
  ignoreInit = TRUE)
  
  # Plot - Right Output ----
  output$plot_bottom <- renderPlot({
    
    # Get Data
    df1 <- my_data()
    
    # Filter by Games Back Input
    df1 <- df1 %>%
      arrange(desc(gameCreation)) %>%
      slice_head(n = input$input_games_back*10)
    
    # Filter to Champion Selection
    df1 <- df1 %>%
      filter_by_champion(my_champion_list = input$input_champ_select)
    
    # Filter to only your position
    df1 <- df1 %>%
      filter(my_position==TRUE)
    
    # Calculate Column Indicating it's the chosen summoner  
    df1 <- df1 %>%
      mutate(me=case_when(summonerName==isolate(input$input_summoner_name) ~ TRUE,
                          TRUE ~ FALSE))
    
    # Change Values and Column Names for Display
    df1 <- df1 %>%
      mutate(me = case_when(me==TRUE ~ 'Myself',TRUE ~ 'Opposing Laner')) %>% 
      rename(Player = me) %>% 
      mutate(win = case_when(win=='True' ~ 'Win',TRUE ~ 'Loss')) %>% 
      rename(`Result` = win) %>% 
      rename(`KDA` = kda)
    
    
    # Manually Order Positions
    df1$Result <- factor(df1$Result,
                       levels=c("Win", "Loss"))
    
    # Roll Up Data to groups for plotting
    df1 <- df1 %>%
      group_by(Player, `Result`) %>%
      summarize(KDA = round(mean(`KDA`, na.rm=TRUE),1), .groups='drop')
    
    # Make Plot
    df1 %>%
      ggplot(aes(fill=Player, y=KDA, x=`Result`)) + 
      geom_bar(position="dodge", stat="identity", show.legend = FALSE) +
      geom_text(aes(label=KDA),color='black', position=position_dodge(width=0.9), vjust=-.35) +
      ylim(0,max(df1%>%select(KDA))+0.5) +
      scale_fill_manual(values=c("green","black")) +
      theme(panel.background = element_rect(fill='#f5f3f0'),
            strip.text.x = element_text(size = 12),
            axis.title.x=element_blank(),
            axis.title.y=element_blank(),
            axis.text=element_text(size=12),
            plot.title = element_text(hjust = 0.5, size=20))
    
  })
  
  #  Plot - Left Output ----
  output$plot_top <- renderPlot({
    
    # Get Data
    df1 <- my_data()
    
    # Filter by Games Back Input
    df1 <- df1 %>%
      arrange(desc(gameCreation)) %>%
      slice_head(n = input$input_games_back*10)
    
    # Filter by Champion Selection
    df1 <- df1 %>%
      filter_by_champion(my_champion_list = input$input_champ_select)
    
    # Change Values and Column Names for Display
    df1 <- df1 %>%
      mutate(my_team = case_when(my_team==TRUE ~ 'Me / My Team',TRUE ~ 'Opposing Team')) %>% 
      rename(`Team` = my_team) %>% 
      rename(`Role` = teamPosition) %>% 
      mutate(Role = str_to_title(Role)) %>%    
      rename(`Solo Kills` = soloKills) %>%
      mutate(Role = case_when(Role=='Utility' ~ 'Support',TRUE ~ Role)) %>% 
      mutate(my_position = case_when(my_position==TRUE ~ 'Me Versus My Lane Opponent',
                                     TRUE ~ 'My Team Versus Their Lane Opponents'))
      
    # Manually Order Positions
    df1$Role <- factor(df1$Role,
                       levels=c("Top", "Jungle","Middle", "Bottom","Support"))
    
    # Filter Out Bad Data
    df1 <- df1 %>%
      filter(is.na(Role)==FALSE)
    
    # Roll Up Data to groups for plotting
    df1 <- df1 %>%
      group_by(Team, Role, my_position, label_color) %>%
      summarize(`Solo Kills` = round(mean(`Solo Kills`, na.rm=TRUE),1), .groups='drop')
      
    # Make Plot
    df1 %>% 
      ggplot(aes(fill=Team, y=`Solo Kills`, x=Role)) + 
      geom_bar(position="dodge", stat="identity", show.legend = FALSE) +
      geom_text(aes(label=`Solo Kills`),color='black', position=position_dodge(width=0.9), vjust=-.35) +
      # scale_colour_manual(values=c("white", "black")) +
      # scale_y_continuous(labels=abs) +
      ylim(0,max(df1%>%select(`Solo Kills`))+0.25) +
      scale_fill_manual(values=c("green","black")) +
      theme(legend.position = "top",
            panel.background = element_rect(fill='#f5f3f0'),
            strip.text.x = element_text(size = 12),
            axis.title.x=element_blank(),
            axis.title.y=element_blank(),
            axis.text=element_text(size=12),
            plot.title = element_text(hjust = 0.5, size=20)) +
      facet_wrap(~my_position, ncol = 1)
  })
  
  # Header Story Output ----
  output$output_story <- renderUI({
    input$button_reload
    
    h1(style="text-align: center",
       paste0(isolate(input$input_summoner_name),
              "'s Team Sucks"))
  })
  
  # Help Text Selection Output ----
  output$output_selection_helptext <- renderUI({
    
    # Get Data
    df1 <- my_data()
    
    # Filter by Games Back Input
    df1 <- df1 %>%
      arrange(desc(gameCreation)) %>%
      slice_head(n = input$input_games_back*10)
    
    # Filter by Champion Selection
    df1 <- df1 %>%
      filter_by_champion(my_champion_list = input$input_champ_select)
    
    # HTML Output Text
    HTML(paste0('<span class="help-block">',nrow(df1)/10,
                ' in the last ',input$input_games_back,
                ' games played on selected champion(s)</span>'))
  })
}

# Complete app with UI and server components
shinyApp(ui, server)